geolife8:
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 12
  max_input_length: 12
  test_prediction_length: 12
  batch_size: 256
  device: cuda
  max_epochs: 6
  block_size: 25
  learning_rate: 1.e-4
  weight_decay: 5.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 20
  lr_decay_epochs: 16
  min_lr: 5.e-10
  seed: 42
  data_dir: ./data
  dataset: geolife
  resolution: 8
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 5
  continuity: False
  beam_width: 5
  store_predictions: True
  window_size: 300
geolife9:
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 12
  max_input_length: 12
  test_prediction_length: 12
  batch_size: 256
  device: cuda
  max_epochs: 6
  block_size: 25
  learning_rate: 1.e-3
  weight_decay: 5.e-2
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 20
  lr_decay_epochs: 5
  min_lr: 1.e-10
  seed: 42
  data_dir: ./data
  dataset: geolife
  resolution: 9
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
  continuity: False
  beam_width: 5
  store_predictions: True
  window_size: 300
geolife10:
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 12
  max_input_length: 12
  test_prediction_length: 12
  batch_size: 256
  device: cuda
  max_epochs: 6
  block_size: 25
  learning_rate: 1.e-3
  weight_decay: 8.e-2
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 20
  lr_decay_epochs: 5
  min_lr: 1.e-10
  seed: 42
  data_dir: ./data
  dataset: geolife
  resolution: 10
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
  continuity: False
  beam_width: 5
  store_predictions: True
  window_size: 300